// Mock data for the Design Marketplace

export const categories = [
  { id: 1, name: 'Baju', icon: '👕', count: 24 },
  { id: 2, name: 'Celana', icon: '👖', count: 18 },
  { id: 3, name: 'Jaket & Sweater', icon: '🧥', count: 16 },
  { id: 4, name: '1 Set', icon: '👔', count: 12 },
];

export const designs = [
  {
    id: 1,
    title: 'Urban Street Vibes',
    description: 'Desain kaos bergaya urban street art dengan kombinasi warna bold dan elemen graffiti modern. Cocok untuk brand streetwear dan clothing line.',
    price: 150000,
    category_id: 1,
    category: 'Baju',
    tags: ['streetwear', 'urban', 'graffiti', 'bold'],
    preview_image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&q=80',
    mockup_images: [
      'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&q=80',
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80',
    ],
    file_formats: ['PSD', 'PNG', 'SVG'],
    created_by: 'DesignStudio',
    created_at: '2026-03-10',
    downloads: 142,
    rating: 4.8,
    reviews: 28,
  },
  {
    id: 2,
    title: 'Minimalist Nature',
    description: 'Desain minimalis bertema alam dengan garis-garis halus dan palet warna earth tone. Sempurna untuk produk eco-friendly.',
    price: 120000,
    category_id: 1,
    category: 'Baju',
    tags: ['minimalist', 'nature', 'earth', 'clean'],
    preview_image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec515c7?w=600&q=80',
    mockup_images: [
      'https://images.unsplash.com/photo-1503342217505-b0a15ec515c7?w=800&q=80',
    ],
    file_formats: ['PSD', 'AI', 'PNG'],
    created_by: 'DesignStudio',
    created_at: '2026-03-08',
    downloads: 98,
    rating: 4.6,
    reviews: 15,
  },
  {
    id: 3,
    title: 'Retro Wave Collection',
    description: 'Koleksi desain bergaya retro synthwave dengan gradien neon dan elemen 80s. Ideal untuk kaos, poster, dan merchandise.',
    price: 200000,
    category_id: 1,
    category: 'Baju',
    tags: ['retro', 'synthwave', 'neon', '80s'],
    preview_image: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=600&q=80',
    mockup_images: [
      'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800&q=80',
    ],
    file_formats: ['PSD', 'PNG', 'SVG', 'AI'],
    created_by: 'DesignStudio',
    created_at: '2026-03-05',
    downloads: 215,
    rating: 4.9,
    reviews: 42,
  },
  {
    id: 4,
    title: 'Tote Bag Floral',
    description: 'Desain tas tote bag dengan motif bunga tropis yang elegan. Pattern seamless siap cetak untuk berbagai ukuran tas.',
    price: 100000,
    category_id: 1,
    category: 'Baju',
    tags: ['floral', 'tropical', 'tote bag', 'pattern'],
    preview_image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&q=80',
    mockup_images: [
      'https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&q=80',
    ],
    file_formats: ['PSD', 'PNG'],
    created_by: 'DesignStudio',
    created_at: '2026-03-12',
    downloads: 76,
    rating: 4.5,
    reviews: 12,
  },
  {
    id: 5,
    title: 'Snapback Cap Logo',
    description: 'Desain logo untuk topi snapback dengan style sporty dan modern. Termasuk mockup 3D dari berbagai sudut.',
    price: 85000,
    category_id: 3,
    category: 'Jaket & Sweater',
    tags: ['snapback', 'logo', 'sporty', 'cap'],
    preview_image: 'https://images.unsplash.com/photo-1588850561407-ed78c334e67a?w=600&q=80',
    mockup_images: [
      'https://images.unsplash.com/photo-1588850561407-ed78c334e67a?w=800&q=80',
    ],
    file_formats: ['PSD', 'AI', 'SVG'],
    created_by: 'DesignStudio',
    created_at: '2026-03-01',
    downloads: 54,
    rating: 4.3,
    reviews: 8,
  },
  {
    id: 6,
    title: 'Coffee Mug Typography',
    description: 'Desain gelas kopi dengan typography kreatif dan quotes inspiratif. Set berisi 5 variasi desain berbeda.',
    price: 95000,
    category_id: 1,
    category: 'Baju',
    tags: ['mug', 'typography', 'coffee', 'quotes'],
    preview_image: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=600&q=80',
    mockup_images: [
      'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=800&q=80',
    ],
    file_formats: ['PSD', 'PNG', 'SVG'],
    created_by: 'DesignStudio',
    created_at: '2026-02-28',
    downloads: 112,
    rating: 4.7,
    reviews: 22,
  },
  {
    id: 7,
    title: 'Holographic Sticker Pack',
    description: 'Pack sticker holographic dengan 20 desain unik bertema space dan futuristik. Siap cetak untuk die-cut sticker.',
    price: 75000,
    category_id: 1,
    category: 'Baju',
    tags: ['holographic', 'sticker', 'space', 'futuristic'],
    preview_image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&q=80',
    mockup_images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80',
    ],
    file_formats: ['PSD', 'PNG', 'SVG'],
    created_by: 'DesignStudio',
    created_at: '2026-03-14',
    downloads: 189,
    rating: 4.9,
    reviews: 35,
  },
  {
    id: 8,
    title: 'Movie Poster Cinematic',
    description: 'Template poster bergaya sinematik Hollywood. Mudah diedit dan cocok untuk poster film, event, atau promosi.',
    price: 180000,
    category_id: 4,
    category: '1 Set',
    tags: ['poster', 'cinematic', 'movie', 'template'],
    preview_image: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=600&q=80',
    mockup_images: [
      'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800&q=80',
    ],
    file_formats: ['PSD', 'AI'],
    created_by: 'DesignStudio',
    created_at: '2026-03-09',
    downloads: 67,
    rating: 4.4,
    reviews: 11,
  },
  {
    id: 9,
    title: 'Japanese Wave Art',
    description: 'Desain seni Jepang dengan motif ombak klasik yang dipadukan dengan sentuhan modern. Cocok untuk kaos dan poster.',
    price: 165000,
    category_id: 1,
    category: 'Baju',
    tags: ['japanese', 'wave', 'art', 'traditional'],
    preview_image: 'https://images.unsplash.com/photo-1545239351-ef35f43d514b?w=600&q=80',
    mockup_images: [
      'https://images.unsplash.com/photo-1545239351-ef35f43d514b?w=800&q=80',
    ],
    file_formats: ['PSD', 'PNG', 'AI'],
    created_by: 'DesignStudio',
    created_at: '2026-03-11',
    downloads: 134,
    rating: 4.8,
    reviews: 26,
  },
  {
    id: 10,
    title: 'Geometric Abstract',
    description: 'Desain abstrak geometris dengan warna-warna vibrant. Set berisi pattern dan standalone design untuk berbagai produk.',
    price: 130000,
    category_id: 4,
    category: '1 Set',
    tags: ['geometric', 'abstract', 'colorful', 'pattern'],
    preview_image: 'https://images.unsplash.com/photo-1550859492-d5da9d8e45f3?w=600&q=80',
    mockup_images: [
      'https://images.unsplash.com/photo-1550859492-d5da9d8e45f3?w=800&q=80',
    ],
    file_formats: ['PSD', 'SVG', 'PNG'],
    created_by: 'DesignStudio',
    created_at: '2026-03-06',
    downloads: 91,
    rating: 4.6,
    reviews: 18,
  },
  {
    id: 11,
    title: 'Eco Friendly Badge',
    description: 'Koleksi badge dan emblem bertema ramah lingkungan. Cocok untuk sticker, label produk, dan branding eco-friendly.',
    price: 60000,
    category_id: 1,
    category: 'Baju',
    tags: ['eco', 'badge', 'emblem', 'green'],
    preview_image: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=600&q=80',
    mockup_images: [
      'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=800&q=80',
    ],
    file_formats: ['SVG', 'PNG', 'AI'],
    created_by: 'DesignStudio',
    created_at: '2026-03-13',
    downloads: 203,
    rating: 4.7,
    reviews: 31,
  },
  {
    id: 12,
    title: 'Vintage Travel Poster',
    description: 'Desain poster travel bergaya vintage tahun 50-an. Ilustrasi hand-drawn dengan color palette klasik yang hangat.',
    price: 145000,
    category_id: 4,
    category: '1 Set',
    tags: ['vintage', 'travel', 'retro', 'illustration'],
    preview_image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80',
    mockup_images: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    ],
    file_formats: ['PSD', 'AI', 'PNG'],
    created_by: 'DesignStudio',
    created_at: '2026-03-07',
    downloads: 88,
    rating: 4.5,
    reviews: 14,
  },
  {
    id: 13,
    title: 'Skull & Roses Gothic',
    description: 'Desain gothic dengan kombinasi tengkorak dan mawar. Sangat cocok untuk brand streetwear, metal merchandise, dan tattoo art.',
    price: 175000,
    category_id: 1,
    category: 'Baju',
    tags: ['gothic', 'skull', 'roses', 'dark'],
    preview_image: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=600&q=80',
    mockup_images: [
      'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&q=80',
    ],
    file_formats: ['PSD', 'PNG', 'AI', 'SVG'],
    created_by: 'DesignStudio',
    created_at: '2026-03-15',
    downloads: 167,
    rating: 4.9,
    reviews: 38,
  },
  {
    id: 14,
    title: 'Tropical Paradise Pattern',
    description: 'Pattern seamless bertema tropis dengan daun monstera, bunga hibiscus, dan burung toucan. Cocok untuk tas, baju, dan aksesoris.',
    price: 110000,
    category_id: 1,
    category: 'Baju',
    tags: ['tropical', 'pattern', 'nature', 'colorful'],
    preview_image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80',
    mockup_images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80',
    ],
    file_formats: ['PSD', 'PNG', 'SVG'],
    created_by: 'DesignStudio',
    created_at: '2026-03-16',
    downloads: 89,
    rating: 4.6,
    reviews: 16,
  },
  {
    id: 15,
    title: 'Neon Cyberpunk City',
    description: 'Ilustrasi kota cyberpunk dengan efek neon glow. Cocok untuk poster, kaos, dan wall art. Resolusi ultra tinggi.',
    price: 250000,
    category_id: 4,
    category: '1 Set',
    tags: ['cyberpunk', 'neon', 'city', 'futuristic'],
    preview_image: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&q=80',
    mockup_images: [
      'https://images.unsplash.com/photo-1563089145-599997674d42?w=800&q=80',
    ],
    file_formats: ['PSD', 'PNG', 'TIFF'],
    created_by: 'DesignStudio',
    created_at: '2026-03-17',
    downloads: 156,
    rating: 4.9,
    reviews: 44,
  },
  {
    id: 16,
    title: 'Kawaii Sticker Set',
    description: 'Set sticker kawaii lucu dengan 30 karakter unik. Cocok untuk planner, journal, laptop, dan hadiah.',
    price: 55000,
    category_id: 1,
    category: 'Baju',
    tags: ['kawaii', 'cute', 'character', 'japanese'],
    preview_image: 'https://images.unsplash.com/photo-1572566929650-3301a5732f52?w=600&q=80',
    mockup_images: [
      'https://images.unsplash.com/photo-1572566929650-3301a5732f52?w=800&q=80',
    ],
    file_formats: ['PSD', 'PNG', 'SVG'],
    created_by: 'DesignStudio',
    created_at: '2026-03-18',
    downloads: 234,
    rating: 4.8,
    reviews: 52,
  },
  {
    id: 17,
    title: 'Bucket Hat Embroidery',
    description: 'Desain embroidery untuk bucket hat dengan motif bunga cherry blossom. Termasuk file digitize untuk mesin bordir.',
    price: 95000,
    category_id: 3,
    category: 'Jaket & Sweater',
    tags: ['bucket hat', 'embroidery', 'cherry blossom', 'floral'],
    preview_image: 'https://images.unsplash.com/photo-1556306535-0f09a537f0a3?w=600&q=80',
    mockup_images: [
      'https://images.unsplash.com/photo-1556306535-0f09a537f0a3?w=800&q=80',
    ],
    file_formats: ['PSD', 'DST', 'PNG'],
    created_by: 'DesignStudio',
    created_at: '2026-03-14',
    downloads: 45,
    rating: 4.4,
    reviews: 9,
  },
  {
    id: 18,
    title: 'Ceramic Mug Watercolor',
    description: 'Desain mug keramik dengan teknik watercolor abstrak. Set berisi 8 variasi warna yang cantik dan elegan.',
    price: 85000,
    category_id: 1,
    category: 'Baju',
    tags: ['watercolor', 'ceramic', 'abstract', 'elegant'],
    preview_image: 'https://images.unsplash.com/photo-1577937927133-66ef06acdf18?w=600&q=80',
    mockup_images: [
      'https://images.unsplash.com/photo-1577937927133-66ef06acdf18?w=800&q=80',
    ],
    file_formats: ['PSD', 'PNG'],
    created_by: 'DesignStudio',
    created_at: '2026-03-13',
    downloads: 78,
    rating: 4.5,
    reviews: 13,
  },
  {
    id: 19,
    title: 'Vaporwave Aesthetic',
    description: 'Desain estetik vaporwave dengan patung Yunani, palm trees, dan grid neon. Sempurna untuk kaos dan poster.',
    price: 140000,
    category_id: 1,
    category: 'Baju',
    tags: ['vaporwave', 'aesthetic', 'retro', 'pink'],
    preview_image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&q=80',
    mockup_images: [
      'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80',
    ],
    file_formats: ['PSD', 'PNG', 'AI'],
    created_by: 'DesignStudio',
    created_at: '2026-03-12',
    downloads: 121,
    rating: 4.7,
    reviews: 24,
  },
  {
    id: 20,
    title: 'Enamel Pin Collection',
    description: 'Koleksi desain enamel pin dengan 15 desain unik bertema food, animal, dan pop culture. Siap produksi.',
    price: 125000,
    category_id: 4,
    category: '1 Set',
    tags: ['enamel pin', 'cute', 'collection', 'pop culture'],
    preview_image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&q=80',
    mockup_images: [
      'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&q=80',
    ],
    file_formats: ['AI', 'SVG', 'PNG'],
    created_by: 'DesignStudio',
    created_at: '2026-03-11',
    downloads: 67,
    rating: 4.6,
    reviews: 11,
  },
  {
    id: 21,
    title: 'Motivational Quote Pack',
    description: 'Paket 10 desain poster motivasi dengan typography modern. Cocok untuk wall art, feed Instagram, dan cetak poster.',
    price: 90000,
    category_id: 4,
    category: '1 Set',
    tags: ['motivational', 'typography', 'quotes', 'modern'],
    preview_image: 'https://images.unsplash.com/photo-1504805572947-34fad45aed93?w=600&q=80',
    mockup_images: [
      'https://images.unsplash.com/photo-1504805572947-34fad45aed93?w=800&q=80',
    ],
    file_formats: ['PSD', 'PNG', 'PDF'],
    created_by: 'DesignStudio',
    created_at: '2026-03-10',
    downloads: 198,
    rating: 4.7,
    reviews: 33,
  },
  {
    id: 22,
    title: 'Anime Character Kaos',
    description: 'Desain karakter anime original dengan gaya chibi. Termasuk versi full color dan outline untuk berbagai warna kaos.',
    price: 160000,
    category_id: 1,
    category: 'Baju',
    tags: ['anime', 'chibi', 'character', 'illustration'],
    preview_image: 'https://images.unsplash.com/photo-1534361960057-19889db9621e?w=600&q=80',
    mockup_images: [
      'https://images.unsplash.com/photo-1534361960057-19889db9621e?w=800&q=80',
    ],
    file_formats: ['PSD', 'PNG', 'AI'],
    created_by: 'DesignStudio',
    created_at: '2026-03-09',
    downloads: 145,
    rating: 4.8,
    reviews: 29,
  },
  {
    id: 23,
    title: 'Drawstring Bag Pattern',
    description: 'Desain pattern serut bag dengan motif marble dan gold foil. Elegan dan modern, cocok untuk produk premium.',
    price: 90000,
    category_id: 1,
    category: 'Baju',
    tags: ['drawstring', 'marble', 'gold', 'premium'],
    preview_image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80',
    mockup_images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80',
    ],
    file_formats: ['PSD', 'PNG'],
    created_by: 'DesignStudio',
    created_at: '2026-03-08',
    downloads: 52,
    rating: 4.3,
    reviews: 7,
  },
  {
    id: 24,
    title: 'Camping Adventure Badge',
    description: 'Koleksi badge dan patch outdoor adventure. 12 desain bertema camping, hiking, dan mountain. Cocok untuk sticker dan emblem.',
    price: 70000,
    category_id: 1,
    category: 'Baju',
    tags: ['camping', 'adventure', 'outdoor', 'badge'],
    preview_image: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&q=80',
    mockup_images: [
      'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&q=80',
    ],
    file_formats: ['SVG', 'PNG', 'AI', 'EPS'],
    created_by: 'DesignStudio',
    created_at: '2026-03-07',
    downloads: 176,
    rating: 4.8,
    reviews: 36,
  },
];

export const users = [
  { id: 1, name: 'Admin Developer', email: 'dev@designbaju.com', role: 'developer', created_at: '2026-01-01' },
  { id: 2, name: 'Design Manager', email: 'manager@designbaju.com', role: 'manager', created_at: '2026-01-15' },
  { id: 3, name: 'John Customer', email: 'john@email.com', role: 'user', created_at: '2026-02-01' },
  { id: 4, name: 'Sarah Designer', email: 'sarah@email.com', role: 'manager', created_at: '2026-02-10' },
  { id: 5, name: 'Budi Santoso', email: 'budi@email.com', role: 'user', created_at: '2026-02-20' },
  { id: 6, name: 'Rina Wati', email: 'rina@email.com', role: 'user', created_at: '2026-03-01' },
];

export const orders = [
  {
    id: 'ORD-001',
    user_id: 3,
    user_name: 'John Customer',
    items: [
      { design_id: 1, title: 'Urban Street Vibes', price: 150000 },
      { design_id: 7, title: 'Holographic Sticker Pack', price: 75000 },
    ],
    total_price: 225000,
    status: 'completed',
    payment_method: 'Bank Transfer',
    created_at: '2026-03-14',
  },
  {
    id: 'ORD-002',
    user_id: 5,
    user_name: 'Budi Santoso',
    items: [
      { design_id: 3, title: 'Retro Wave Collection', price: 200000 },
    ],
    total_price: 200000,
    status: 'paid',
    payment_method: 'E-Wallet',
    created_at: '2026-03-15',
  },
  {
    id: 'ORD-003',
    user_id: 6,
    user_name: 'Rina Wati',
    items: [
      { design_id: 6, title: 'Coffee Mug Typography', price: 95000 },
      { design_id: 11, title: 'Eco Friendly Badge', price: 60000 },
      { design_id: 9, title: 'Japanese Wave Art', price: 165000 },
    ],
    total_price: 320000,
    status: 'processing',
    payment_method: 'Credit Card',
    created_at: '2026-03-15',
  },
  {
    id: 'ORD-004',
    user_id: 3,
    user_name: 'John Customer',
    items: [
      { design_id: 8, title: 'Movie Poster Cinematic', price: 180000 },
    ],
    total_price: 180000,
    status: 'pending',
    payment_method: null,
    created_at: '2026-03-16',
  },
];

export const customOrders = [
  {
    id: 'CUST-001',
    user_id: 3,
    user_name: 'John Customer',
    product_type: 'Kaos',
    description: 'Desain kaos untuk event band metal lokal. Tema gothic dengan skull dan roses. Warna dominan hitam dan merah.',
    reference_image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec515c7?w=400&q=80',
    budget: 500000,
    deadline: '2026-03-25',
    status: 'processing',
    created_at: '2026-03-10',
  },
  {
    id: 'CUST-002',
    user_id: 5,
    user_name: 'Budi Santoso',
    product_type: 'Logo & Branding',
    description: 'Logo untuk coffee shop baru. Konsep minimalis, modern, dengan elemen kopi. Nama brand: KopiKita.',
    reference_image: null,
    budget: 750000,
    deadline: '2026-03-30',
    status: 'pending',
    created_at: '2026-03-14',
  },
  {
    id: 'CUST-003',
    user_id: 6,
    user_name: 'Rina Wati',
    product_type: 'Poster',
    description: 'Poster untuk acara music festival. Ukuran A2, full color, tema tropical vibes dengan palm trees.',
    reference_image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&q=80',
    budget: 350000,
    deadline: '2026-04-05',
    status: 'completed',
    created_at: '2026-03-05',
  },
];

export const testimonials = [
  {
    id: 1,
    name: 'Andi Pratama',
    role: 'Owner Clothing Brand',
    avatar: '🧑‍💼',
    rating: 5,
    text: 'Desain-desainnya sangat berkualitas dan siap cetak. Sudah beli lebih dari 20 desain untuk brand streetwear saya. Sangat recommended!',
  },
  {
    id: 2,
    name: 'Maya Sari',
    role: 'Event Organizer',
    avatar: '👩‍🎨',
    rating: 5,
    text: 'Custom order untuk poster event kami hasilnya luar biasa. Prosesnya cepat dan desainernya sangat komunikatif. Pasti order lagi!',
  },
  {
    id: 3,
    name: 'Reza Firmansyah',
    role: 'Coffee Shop Owner',
    avatar: '☕',
    rating: 4,
    text: 'Beli desain mug dan sticker untuk merchandise coffee shop. Kualitas file-nya tinggi dan harganya sangat terjangkau.',
  },
  {
    id: 4,
    name: 'Siti Nurhaliza',
    role: 'Online Shop Owner',
    avatar: '🛍️',
    rating: 5,
    text: 'Platform terbaik untuk beli desain digital. File formatnya lengkap, resolusi tinggi, dan yang paling penting lisensi komersialnya jelas.',
  },
  {
    id: 5,
    name: 'Dimas Aditya',
    role: 'Freelance Designer',
    avatar: '🎨',
    rating: 5,
    text: 'Sebagai desainer, saya kagum dengan kualitas desain di sini. Sangat menginspirasi dan membantu klien saya untuk brainstorming.',
  },
  {
    id: 6,
    name: 'Lisa Permata',
    role: 'Marketing Manager',
    avatar: '📊',
    rating: 4,
    text: 'Kami menggunakan desain dari sini untuk merchandise perusahaan. Proses pembelian mudah, download cepat, dan kualitas premium.',
  },
];

export const designReviews = [
  { id: 1, design_id: 1, user_name: 'Andi P.', rating: 5, text: 'File kualitasnya luar biasa, detail banget!', date: '2026-03-12' },
  { id: 2, design_id: 1, user_name: 'Budi S.', rating: 5, text: 'Langsung bisa dipakai, sangat puas.', date: '2026-03-11' },
  { id: 3, design_id: 1, user_name: 'Maya S.', rating: 4, text: 'Bagus, tapi wish ada lebih banyak variasi warna.', date: '2026-03-10' },
  { id: 4, design_id: 3, user_name: 'Reza F.', rating: 5, text: 'Retro vibes-nya kena banget! Love it.', date: '2026-03-08' },
  { id: 5, design_id: 3, user_name: 'Dimas A.', rating: 5, text: 'Best purchase ever, file lengkap dan rapi.', date: '2026-03-07' },
  { id: 6, design_id: 7, user_name: 'Lisa P.', rating: 5, text: 'Sticker pack terbaik! 20 desain semua keren.', date: '2026-03-15' },
  { id: 7, design_id: 7, user_name: 'Siti N.', rating: 5, text: 'Holographic effectnya cakep banget di sticker.', date: '2026-03-14' },
  { id: 8, design_id: 9, user_name: 'Andi P.', rating: 5, text: 'Japanese art nya autentik, sangat detail.', date: '2026-03-13' },
  { id: 9, design_id: 13, user_name: 'Dimas A.', rating: 5, text: 'Gothic vibes nya perfect untuk brand saya!', date: '2026-03-16' },
  { id: 10, design_id: 15, user_name: 'Reza F.', rating: 5, text: 'Cyberpunk ini keren banget, resolusi tinggi!', date: '2026-03-18' },
];

export const promoCodes = [
  { code: 'WELCOME20', discount: 20, type: 'percentage', minPurchase: 100000, maxDiscount: 50000, active: true, description: 'Diskon 20% untuk pembelian pertama' },
  { code: 'HEMAT50K', discount: 50000, type: 'fixed', minPurchase: 200000, maxDiscount: 50000, active: true, description: 'Potongan Rp50.000' },
  { code: 'BUNDLE30', discount: 30, type: 'percentage', minPurchase: 300000, maxDiscount: 100000, active: true, description: 'Diskon 30% untuk pembelian 3+ desain' },
];

export const portfolioItems = [
  {
    id: 1,
    title: 'Brand Identity - KopiKita',
    description: 'Branding lengkap untuk coffee shop lokal termasuk logo, packaging, dan merchandise.',
    category: 'Branding',
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80',
    client: 'KopiKita Coffee',
    year: '2026',
  },
  {
    id: 2,
    title: 'Streetwear Collection - RVLT',
    description: 'Koleksi 12 desain kaos untuk brand streetwear lokal. Tema urban dan graffiti art.',
    category: 'Clothing',
    image: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=800&q=80',
    client: 'RVLT Clothing',
    year: '2026',
  },
  {
    id: 3,
    title: 'Music Festival Poster',
    description: 'Seri poster untuk festival musik tahunan dengan gaya retro tropical.',
    category: '1 Set',
    image: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80',
    client: 'Soundwave Festival',
    year: '2025',
  },
  {
    id: 4,
    title: 'Sticker Pack - Tokped Store',
    description: 'Custom sticker pack untuk bonus pembelian di online store.',
    category: 'Baju',
    image: 'https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=800&q=80',
    client: 'PixelStore',
    year: '2025',
  },
  {
    id: 5,
    title: 'Ceramic Mug Series',
    description: 'Seri desain gelas keramik premium dengan tema watercolor abstract.',
    category: 'Product',
    image: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=800&q=80',
    client: 'MugCraft Indonesia',
    year: '2025',
  },
  {
    id: 6,
    title: 'Eco Merchandise Line',
    description: 'Desain merchandise ramah lingkungan termasuk tote bag, tumbler, dan notebook cover.',
    category: '1 Set',
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&q=80',
    client: 'GreenLife Co.',
    year: '2026',
  },
];

export const faqItems = [
  {
    category: 'Pembelian',
    items: [
      {
        q: 'Bagaimana cara membeli desain?',
        a: 'Pilih desain yang Anda inginkan dari katalog, tambahkan ke keranjang, lalu lakukan checkout. Setelah pembayaran dikonfirmasi, file desain bisa langsung didownload dari dashboard.',
      },
      {
        q: 'Metode pembayaran apa saja yang tersedia?',
        a: 'Kami menerima pembayaran via Bank Transfer (BCA, Mandiri, BNI, BRI), Kartu Kredit/Debit (Visa, Mastercard, JCB), dan E-Wallet (GoPay, OVO, DANA, ShopeePay).',
      },
      {
        q: 'Apakah bisa menggunakan kode promo?',
        a: 'Ya! Anda bisa memasukkan kode promo saat checkout untuk mendapatkan diskon. Follow Instagram kami untuk info promo terbaru.',
      },
    ],
  },
  {
    category: 'File & Format',
    items: [
      {
        q: 'Format file apa saja yang tersedia?',
        a: 'Setiap desain tersedia dalam berbagai format seperti PSD (Photoshop), AI (Illustrator), SVG (Vector), PNG (Transparent), dan format lainnya sesuai kebutuhan.',
      },
      {
        q: 'Berapa resolusi file yang disediakan?',
        a: 'Semua file desain disediakan dalam resolusi tinggi (300 DPI minimum) yang siap cetak untuk berbagai ukuran produk.',
      },
      {
        q: 'Apakah file bisa diedit?',
        a: 'Ya, file PSD dan AI bisa diedit menggunakan Adobe Photoshop dan Illustrator. File SVG bisa diedit di berbagai aplikasi vector.',
      },
    ],
  },
  {
    category: 'Custom Order',
    items: [
      {
        q: 'Bagaimana proses custom order?',
        a: 'Isi form custom order dengan deskripsi desain, budget, dan deadline. Tim kami akan menghubungi Anda dalam 1-2 hari kerja untuk diskusi lebih lanjut.',
      },
      {
        q: 'Berapa lama waktu pengerjaan custom order?',
        a: 'Tergantung kompleksitas desain, biasanya 3-7 hari kerja. Akan dikomunikasikan saat awal diskusi.',
      },
      {
        q: 'Apakah ada revisi untuk custom order?',
        a: 'Ya, setiap custom order mendapat 3x revisi gratis. Revisi tambahan akan dikenakan biaya sesuai kesepakatan.',
      },
    ],
  },
  {
    category: 'Refund',
    items: [
      {
        q: 'Bagaimana kebijakan refund?',
        a: 'Karena produk digital, refund hanya berlaku jika file yang didownload rusak atau tidak sesuai deskripsi. Klaim refund harus diajukan dalam 7 hari setelah pembelian.',
      },
      {
        q: 'Bagaimana cara mengajukan refund?',
        a: 'Hubungi kami melalui halaman Contact atau email ke support@designbaju.com dengan menyertakan ID order dan alasan refund.',
      },
    ],
  },
];

export const formatPrice = (price) => {
  return new Intl.NumberFormat('id-ID', {
    style: 'currency',
    currency: 'IDR',
    minimumFractionDigits: 0,
  }).format(price);
};

export const statusColors = {
  pending: 'bg-yellow-500/20 text-yellow-400 border-yellow-500/30',
  paid: 'bg-blue-500/20 text-blue-400 border-blue-500/30',
  processing: 'bg-purple-500/20 text-purple-400 border-purple-500/30',
  completed: 'bg-green-500/20 text-green-400 border-green-500/30',
  cancelled: 'bg-red-500/20 text-red-400 border-red-500/30',
  accepted: 'bg-green-500/20 text-green-400 border-green-500/30',
  rejected: 'bg-red-500/20 text-red-400 border-red-500/30',
};
